# Generated by Django 5.2.10 on 2026-01-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loja.produto'),
        ),
    ]
