# Generated by Django 5.2.10 on 2026-02-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_options'),
        ('loja', '0002_vendaitem_nome_produto_alter_vendaitem_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='empresas.empresa'),
        ),
    ]
