# Generated by Django 5.2.10 on 2026-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard Permission',
                'verbose_name_plural': 'Dashboard Permissions',
                'permissions': [('view_dashboard', 'Pode ver o Dashboard')],
            },
        ),
    ]
