# Generated by Django 5.2.10 on 2026-02-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('empresas', '0002_alter_empresa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('MARCADO', 'Marcado'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou')], default='MARCADO', max_length=20),
        ),
    ]
