# Generated by Django 5.2.14 on 2026-05-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_empresa_servico_empresa_and_more'),
        ('clientes', '0002_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
