# Generated by Django 5.2.10 on 2026-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_vendaitem_nome_produto_alter_vendaitem_produto'),
        ('produtos', '0002_migrar_para_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto (legacy)',
                'verbose_name_plural': 'Produtos (legacy)',
                'db_table': 'produtos_produto',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('loja.produto',),
        ),
    ]
