# Generated by Django 5.2.10 on 2026-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('duracao_min', models.PositiveIntegerField(default=60, help_text='Duração em minutos (para agenda).')),
                ('preco_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio (para lucro real).', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
