# Generated by Django 5.2.14 on 2026-05-15 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_alter_empresa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Canal Principal', max_length=120)),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=64)),
                ('waba_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_token', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(blank=True, default='', max_length=64)),
                ('to_phone', models.CharField(max_length=32)),
                ('template_name', models.CharField(max_length=120)),
                ('language_code', models.CharField(default='pt_BR', max_length=16)),
                ('components_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=16)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('proxima_tentativa_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('meta_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.whatsappcanal')),
            ],
            options={
                'ordering': ['-criado_em'],
                'permissions': [('manage_whatsapp_outbox', 'Pode gerenciar fila de WhatsApp')],
            },
        ),
    ]
